[package]
name = "units"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
path = "src/lib.rs"
proc-macro = true

[dependencies]
quote = "1.0.8"
syn = { version = "2.0.18", features = ["full"] }

